name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.5+3
  animated_splash_screen: ^1.3.0
  bottom_navy_bar: ^6.1.0
  ionicons: ^0.2.2
  bulleted_list: ^0.0.1
  carousel_slider: ^5.0.0
  double_back_to_close_app: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  bdd_widget_test: ^1.2.1
  build_runner: ^2.4.9
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
   - images/
   - assets/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
